
language: c
sudo: false

os:
  - osx
  #- linux

compiler:
  - gcc
  #- clang

addons:
  apt:
    packages:
      - libatlas-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/openblas; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install argp-standalone ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind ; fi

script:
  - ./configure --download-cmake --debug --with-precision=single && make && valgrind ./scripts/test.sh
  #- ./configure --download-cmake --with-precision=single && make && ./scripts/test.sh
  #- ./configure --download-cmake --with-precision=double && make && ./scripts/test.sh
